FROM node:20-alpine

WORKDIR /app

ARG APP_PATH
COPY package.json ./
COPY ${APP_PATH}/package.json ./${APP_PATH}/

RUN npm install

COPY ${APP_PATH} ./${APP_PATH}

WORKDIR /app/${APP_PATH}

EXPOSE 5173 5174

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
